# Generated by Django 4.0.3 on 2022-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_image', models.ImageField(upload_to='movie/images')),
                ('movie_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
